name = "pelu-api"
main = "src/index.ts"
compatibility_date = "2026-05-18"
observability = { enabled = true }

routes = [
  { pattern = "pelu.tobywu.org", custom_domain = true }
]

[[kv_namespaces]]
binding = "PELU_USAGE_KV"
id = "2115c5d710e146189c8ce52e26669212"
